# Generated by Django 5.1.5 on 2025-03-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('service_provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_provider_name', models.CharField(db_index=True, max_length=50)),
                ('service_category', models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Repair Technician', 'Repair Technician'), ('Cleaner', 'Cleaner')], db_index=True, max_length=50)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Repair Technician', 'Repair Technician'), ('Cleaner', 'Cleaner')], db_index=True, max_length=50)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.PositiveIntegerField(default=30)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Homeapp.serviceprovider')),
            ],
        ),
    ]
