# Generated by Django 5.1.5 on 2025-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='rating',
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
