# Generated by Django 5.1.5 on 2025-03-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0005_orders_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
